# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170218_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DDD',
            field=models.IntegerField(blank=True, null=True, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
