# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20170224_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemManager',
        ),
    ]
